### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Remingt-on** [eaglx/CallBlocker#2]
Hi. I use it on Android Pie. It's the best blocker app I know!

The only one problem is, that the app doesn't start on boot. In privileges list there is no "start on boot" or something like that. So I have to open the app manually every time I start my phone. Could you fix it?

**Comment by eaglx** [comment]
Hi, thank you 👍

The fix is included in [the recent version](https://github.com/eaglx/CallBlocker/releases/tag/v0.2.15). 

- After system booting, the app will start after a while (~2min). I think the reason is that a phone needs to be fully launched.
- This new version is very first one that is not in debug mode. So you should probably uninstall the previous version before installing the new one (you should backup your rules first).
